import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { BotProvider } from "@/context/BotContext";

export const metadata = {
  title: "Scissor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BotProvider>
          <div>
            <Toaster position="top-center" />
            <Navbar />
            <main>{children}</main>
            <Footer />
          </div>
        </BotProvider>
      </body>
    </html>
  );
}
